version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: s3-presignedurl
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - local-dev-net
    restart: unless-stopped
#
#  backendwithfrontend:
#    container_name: backendwithfrontend
#    build:
#      context: .
#      dockerfile: Dockerfile-local
#    ports:
#      - 6200:8080
#    command: java -jar app.jar

  minio:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z
    networks:
      - local-dev-net
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command:
      server /data --console-address ":9001" #<- /dataで /dataディレクトリをデータストレージとして使用。 --console-address ":9001"でMiniOの管理コンソールを設定
    ports:
      - 9000:9000 #<- APIアクセス用のポート
      - 9001:9001 #<- 管理コンソールアクセス用
  createbuckets:
    image: minio/mc
    networks:
      - local-dev-net
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 root password;
      /usr/bin/mc mb minio/s3-presignedurl-test;
      /usr/bin/mc anonymous set public minio/s3-presignedurl-test;
      exit 0
      "

networks:
  local-dev-net:
    driver: bridge


volumes:
  postgres: