name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: |
          cd frontend
          npm install

      - name: backend unit test
        run: make backend-test

      - name: frontend unit test
        run: make frontend-test
